"""Pydantic models for the Travel Companion API."""

from .itinerary import (
    Activity,
    AIPlan,
    Budget,
    DayGroup,
    DayPlan,
    Destination,
    GenerationMode,
    ItineraryRequest,
    ItineraryResponse,
    Location,
    OpeningHours,
    OptimizationResult,
    Pace,
    Place,
    PlaceCandidate,
    Preferences,
    QualityReportResponse,
    QualityScoreResponse,
    Route,
    ScheduledActivity,
    Summary,
    TipsRequest,
    TipsResponse,
    TravelMode,
    TripDates,
)

__all__ = [
    "Activity",
    "AIPlan",
    "Budget",
    "DayGroup",
    "DayPlan",
    "Destination",
    "GenerationMode",
    "ItineraryRequest",
    "ItineraryResponse",
    "Location",
    "OpeningHours",
    "OptimizationResult",
    "Pace",
    "Place",
    "PlaceCandidate",
    "Preferences",
    "QualityReportResponse",
    "QualityScoreResponse",
    "Route",
    "ScheduledActivity",
    "Summary",
    "TipsRequest",
    "TipsResponse",
    "TravelMode",
    "TripDates",
]
